= Доклад по Prometheus
Добрый день коллеги, сегодня у нас по плану: +
- Основная информация о прометеи
- Принцип его работы
- Структура его устройства +
- Структура метрик +
- Отличия от InfluxDB +
- Концепция хранения данных +
- Практический пример с нод экспортером и графаной +
- И Практический пример с самописным экспортером +

И так начнем: +

== _Основная информация_:
Prometheus — это база данных, оптимизированная для данных временных рядов и идеальный способ хранения показателей мониторинга.
Prometheus выпустила Cloud Native Computing Foundation (CNCF), что означает отличную интеграцию с другими компонентами CNCF.
Он имеет встроенное обнаружение сервисов, что упрощает его использование в высокодинамичных средах.
Для доступа к данным Prometheus предлагает гибкий язык запросов под названием PromQL.


== _Принцип работы_:

Основой его работы является скрейпинг конечных точек.
Прометей посылает HTTP запрос к точкам(обычно это /metrics), которые указываются в конфиг файле, и если точка может дать
данные нужного формата - Прометей определит ее как объект и с определенным интервалом будет делать запросы

== _Структура_:
Прометей состоит из трех компонентов: +

_Retrieval_ - представляет собой сервис по сбору метрик, именно он ходит по конечным точкам и собирает метрику помещая ее затем в хранилище. +
 Обладает тремя вариантами взятия метрик: +
  - Готовые сервисы экспортеры наподобие node-exporter; +
  - Пользовательские сервисы обладающие способность отдавать данные нужного формата; +
  - Pushgateway сервис куда можно скидывать метрики, когда стандартная модель прометея не применима,
       после того, как метрики попали в прометея оттуда их уже забирает prometheus)+

_Storage_ - сама база данных хранящая в себе данные объектов в виде временных рядов

_HTTP Server_ - представляет API к storage для визуализации в простом встроенным GUI или подключению к Grafana.
Также дает возможность агрегировать и обрабатывать данные различными запросами PromQl

== _Alert Manager_

Также к прометею можно подсоеденить алерт менеджера способного отследить какое либо событие(например значение превысило заданную границу)
и отправить на почту оповещение.

== _Структура метрик_

Прометей собирает метрики человекочитаемоего типа, и они имеют два атрибута: +

HELP - описание метрики, для чего и зачем… +

TYPE - один из трех встроенных типов метрики +
 - Counter - сколько раз что то произошло…(обязательно должен расти) +
 - Gauge - какое текущее значение чего то…(но он не показывает развитие метрики) +
 - Histogram - насколько что то большое, насколько что то длинное(могут расчитывать среднее значение и относительные измерения значений) +

== _Отличие от InfluxDB_
Между этими системами есть много общего. +
Обе системы имеют метки (называемые тегами в InfluxDB). +
Обе системы используют в основном одни и те же алгоритмы сжатия данных. +
Обе имеют обширную интеграцию, в том числе друг с другом. +

Но основным преимуществом Prometheus является его огромная поддержка сообщества, основанная на статусе завершенного проекта CNCF
и его мощный язык запросов. Многие приложения, особенно облачные, уже предлагают поддержку Prometheus из коробки.
Также разница в используемых моделях сбора метрик. Прометей собирает метрики push моделью, а инфлюкс pull и в отличии от
других подобных сервисов он не перехватывает отдельные события с привязной ко времени а собирает предварительно
агрегированные метрики о сервисах, а использование push модели дает контроль и централизованность,
а также убирает узкую точку в системе мониторинга. +

== _Концепция хранения_
База данных временных рядов Prometheus хранит данные в высокоэффективном формате на локальном хранилище. +

Прометей работает с парами ключ-значение. Ключ описывает, что мы измеряем, а значение хранит фактическую величину в виде числа.
Также в метрике содержатся разная мета информация(labels).
И он хранит в среднем всего 1-2 байта на выборку, что пользовает прогнозировать какого обьема диск нам нужен. +

Образцы группируются в блоки по два часа. Каждый двухчасовой блок состоит из каталога, содержащего подкаталог chunks,
содержащий все образцы временных рядов для этого временного интервала, файла метаданных и индексного файла
(который индексирует имена метрик и метки временных рядов в каталоге chunks).
Образцы в каталоге chunks по умолчанию сгруппированы в один или несколько сегментных файлов размером до 512 МБ каждый.
Когда серии удаляются через API, записи об удалении сохраняются в отдельных файлах tombstone (вместо немедленного удаления данных из сегментов chunk).
(по умолчанию хранит данные в течении 15 дней, но это можно изменить с помощью флага при запуске программы). +

*Ограничения в использовании*
Файловые системы, не совместимые с POSIX, не поддерживаются для локального хранилища Prometheus, поскольку могут
произойти необратимые повреждения. Файловые системы NFS (включая Aws EF S) не поддерживаются.
NFS может быть совместима с POSIX, но большинство реализаций таковыми не являются. Для надежности настоятельно
рекомендуется использовать локальную файловую систему.
