= Доклад по Prometheus
Добрый день коллеги, сегодня у нас по плану: +
- Основная информация о прометеи
- Принцип работы 
- структура +
- метрики +
- отличия от других инструментов +
- концепцмя хранения +
- структура конфиг файла +
- практический пример с нод экспортером и графаной +
- практический пример с самописным экспортером +
И так начинем: +
== _Основная информация_:
Prometheus - это инструментарий для мониторинга систем и оповещения с открытым исходным кодом,
первоначально созданный в SoundCloud. С момента своего создания в 2012 году многие компании и организации приняли Prometheus,
и у проекта очень активное сообщество разработчиков и пользователей. Это не отдельный проект с открытым исходным кодом,
который поддерживается независимо от какой-либо компании. Чтобы подчеркнуть это и уточнить структуру управления проектом,
Prometheus присоединился к Cloud Native Computing Foundation в 2016 году в качестве второго размещенного проекта после Kubernetes.

Prometheus собирает и хранит свои показатели в виде данных временных рядов, т.е. информация о показателях хранится с отметкой времени,
в которое она была записана, наряду с необязательными парами ключ-значение, называемыми метками.

== _Принцип работы_:

Основной является скрейпинг конечных точек целевых объектов(target и по умолчанию он должна находится по адресу hostaddr/metrics).
Прометей посылает HTTP запрос к точкам, которые указываются в конфиг файле, и если точка можно дать данные нужного формата
то Прометей то определит его как объект и с определенным интервалом будет делать запросы

== _Структура_:

_Retrieval_ - представляет собой сервис по сбору метрик, именно он ходит по конечным точкам и собирает метрику помещая ее затем в хранилище. +
 Обладает тремя вариантами взятия метрик: +
  - Готовые сервисы экспортеры наподобие node-exporter; +
  - Пользовательские сервисы обладающие способность отдавать данные нужного формата; +
  - Pushgateway стороной сервис помогающий собирать данные с пакетов или непредназначенных для этого приложений
    (сервис куда можно скидывать метрики, когда стандартная pull-модель прометея не применима,
       после того, как метрики попали в прометея оттуда их уже забирает prometheus)+

_Storage_ - сама база данных хранящая в себе данные объектов в виде временных рядов

_HTTP Server_ - представляет API к storage для визуализации в простом встроенным GUI или подключению к Graphana.
Также дает возможность агрегировать и обрабатывать данные различными запросами PromQl

== _Alert Manager_

Также к прометею можно подсоеденить алерт менеджера способного отследить какое либо событие(например значение превысило заданную границу) и отправить на почту оповещение.

== _Метрики_

Метрики в промети имеют два атрибута: +

HELP - описание метрики, для чего и зачем… +

TYPE - один из трех встроенных типов метрики +
 - Counter - сколько раз что то произошло…(обязательно должен расти) +
 - Gauge - какое текущее значение чего то…(но он не показывает развитие метрики) +
 - Histogram - насколько что то большое, насколько что то длинное(могут расчитывать среднее значение и относительные измерения значений) +

== _Отличие от Graphite_
Graphite фокусируется на том, чтобы быть пассивной базой данных временных рядов с языком запросов и функциями построения графиков.
Любые другие проблемы решаются внешними компонентами.

Prometheus - это полноценная система мониторинга и определения тенденций, которая включает встроенную и активную очистку,
хранение, запросы, построение графиков и оповещение на основе данных временных рядов. Он обладает знаниями о том,
как должен выглядеть мир (какие конечные точки должны существовать, какие шаблоны временных рядов означают проблемы и т.д.),
и активно пытается найти ошибки.

== _Отличие от InfluxDB_
Между этими системами есть много общего. +
Оба имеют метки (называемые тегами в InfluxDB) для эффективной поддержки многомерных метрик. +
Оба используют в основном одни и те же алгоритмы сжатия данных. Оба имеют обширную интеграцию, в том числе друг с другом. +
У обоих есть крючки, позволяющие вам расширять их дальше, например, анализировать данные в статистических инструментах или
выполнять автоматизированные действия. +
Но использования push модели дает контроль и централизованность, а также убирает узкую точку в системе мониторинга. +

Также в отличии от других подобных сервисов он не перехватывает отдельные события с привязной ко времени а собирает предварительно
агрегированные метрики о сервисах.
В конечном итоге согласованный просмотр данных между репликами. +

Где Прометей лучше: +
 Если вы в первую очередь занимаетесь метриками.
Более мощный язык запросов, функции оповещения и уведомления. +
 InfluxDB поддерживается одной коммерческой компанией по модели с открытым исходным кодом, предлагающей премиальные функции,
такие как кластеризация с закрытым исходным кодом, хостинг и поддержка. +
Prometheus - это полностью открытый исходный код
и независимый проект, поддерживаемый рядом компаний и частных лиц, некоторые из которых также предлагают коммерческие услуги и поддержку.

== _Концепция хранения_
Prometheus включает в себя локальную базу данных временных рядов на диске, но также опционально интегрируется с удаленными системами хранения. +
База данных локальных временных рядов Prometheus хранит данные в пользовательском, высокоэффективном формате в локальном хранилище. +
Модель данных ключ-значение

Прометей работает с парами ключ-значение. Ключ описывает, что мы измеряем, а значение хранит фактическую величину в виде числа.
Также в метрике содержатся разные labels для расширения информации.
Также он хранит в среднем всего 1-2 байта на выборку. И по умолчанию хранит данные в течении 15 дней,
но это можно изменить с помощью указания флага. +

Образцы группируются в блоки по два часа. Каждый двухчасовой блок состоит из каталога, содержащего подкаталог chunks,
содержащий все образцы временных рядов для этого временного интервала, файла метаданных и индексного файла
(который индексирует имена метрик и метки временных рядов в каталоге chunks).
Образцы в каталоге chunks по умолчанию сгруппированы в один или несколько сегментных файлов размером до 512 МБ каждый.
Когда серии удаляются через API, записи об удалении сохраняются в отдельных файлах tombstone (вместо немедленного удаления данных из сегментов chunk).

*Ограничения в использовании*
Файловые системы, не совместимые с POSIX, не поддерживаются для локального хранилища Prometheus, поскольку могут
произойти необратимые повреждения. Файловые системы NFS (включая Aws EF S) не поддерживаются.
NFS может быть совместима с POSIX, но большинство реализаций таковыми не являются. Для надежности настоятельно
рекомендуется использовать локальную файловую систему.

== _Структура конфиг файла_

Конфиг файл является YML файлов и он является основной для работы Прометея вы рассмотрим лишь некоторые из его множества полей. 

Global конфигурация определяет параметры, которые действительны во всех других контекстах конфигурации. Они также служат значениями по умолчанию для других разделов конфигурации. 

Раздел scrape_config определяет набор целевых объектов и параметров, описывающих, как их очистить. В общем случае одна конфигурация очистки определяет одно задание. В расширенных конфигурациях это может измениться.

Целевые объекты могут быть статически сконфигурированы с помощью параметра static_configs или динамически обнаружены с использованием одного из поддерживаемых механизмов обнаружения служб.

tls_config позволяет настраивать соединения TLS. 

Конфигурации Docker SD позволяют извлекать целевые объекты scrape с хостов Docker Engine.

Эта SD-карта обнаруживает “контейнеры” и создаст цель для каждого сетевого IP-адреса и порта, на который настроен контейнер.