global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "app"
    static_configs:
      - targets: ["127.0.0.1:8885"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["127.0.0.1:9100"]